(()=>{
const format=window.fileFormat,doc=window.fileExamples[format];if(format==='html')return;
document.body.classList.add('document-preview',`format-${format}`);document.title=doc.file+' — 飞象老师';
const lesson=document.getElementById('lesson');[...lesson.children].forEach(n=>{n.hidden=true;n.querySelectorAll('[data-commentable]').forEach(el=>el.removeAttribute('data-commentable'));n.removeAttribute('data-commentable');});
const toolbar=document.createElement('div');toolbar.className='document-bar';const name=document.createElement('span');name.textContent=doc.file;toolbar.append(name);
const nav=document.createElement('div');nav.className='document-pagination';const previous=document.createElement('button'),next=document.createElement('button'),count=document.createElement('span');previous.textContent='‹';next.textContent='›';previous.setAttribute('aria-label','上一页');next.setAttribute('aria-label','下一页');nav.append(previous,count,next);toolbar.append(nav);lesson.append(toolbar);
const pages=doc.pages.map((page,index)=>{const article=document.createElement('article');article.className='document-sheet';const title=document.createElement('h1');title.textContent=page.title;const sub=document.createElement('p');sub.className='document-subtitle';sub.textContent=page.subtitle;article.append(title,sub);page.sections.forEach(([heading,text],i)=>{const section=document.createElement('section'),h=document.createElement('h2'),p=document.createElement('p');h.textContent=heading;p.textContent=text;h.dataset.commentable='';p.dataset.commentable='';h.dataset.anchor=`${format}-${index}-${i}-heading`;p.dataset.anchor=`${format}-${index}-${i}-text`;section.append(h,p);article.append(section);});title.dataset.commentable='';title.dataset.anchor=`${format}-${index}-title`;const foot=document.createElement('footer');foot.textContent=`${index+1} / ${doc.pages.length}`;article.append(foot);lesson.append(article);return article;});
let current=0;function show(i){current=i;pages.forEach((p,n)=>p.hidden=n!==i);count.textContent=`${i+1} / ${pages.length}`;previous.disabled=i===0;next.disabled=i===pages.length-1;window.dispatchEvent(new Event('resize'));}previous.onclick=()=>show(current-1);next.onclick=()=>show(current+1);let initial=0;try{const refs=JSON.parse(sessionStorage.getItem('feixiang-workbench-annotations-v1-'+format)||'[]');const id=refs.at(-1)?.anchor?.id||refs.at(-1)?.anchor?.items?.[0]?.id;const page=Number(id?.split('-')[1]);if(Number.isInteger(page)&&page>=0&&page<pages.length)initial=page;}catch{}show(initial);
})();
